image: microsoft/dotnet:latest

variables:
  PROJECT_NAME: "EVE.SingleSignOn.Core"
  CONFIG_TYPE: "Release"
before_script:
  - echo "starting build for $PROJECT_NAME"
stages:
  - package
  - publish

cache:
  key: $CI_BUILD_REF_NAME
  paths:
  - nupkg/


validateBuild:
  stage: package
  before_script:
  - echo "Restoring NuGet Packages & making nuget package..."
  - dotnet restore "src/"
  only:
    - tags
  script:
    - dotnet build "src\$PROJECT_NAME" -c $CONFIG_TYPE -o npk -p:Version=$CI_BUILD_TAG

publishNuget:
  stage: publish
  only:
    - tags
  script:
    - echo 'Publishing NuGet package'
    - cd nupkg
    - dotnet nuget push *.$CI_BUILD_TAG.nupkg $NUGET_KEY -Source https://www.nuget.org/api/v2/package