image: mcr.microsoft.com/dotnet/core/sdk:2.2

variables:
  PROJECT_NAME: "EVE.SingleSignOn.Core"
  CONFIG_TYPE: "Release"
before_script:
  - echo "starting build for $PROJECT_NAME"
stages:
  - package
  - publish

cache:
  key: $CI_BUILD_REF_NAME
  paths:
  - src/$PROJECT_NAME/npk/


validateBuild:
  stage: package
  before_script:
  - echo "Restoring NuGet Packages & making nuget package..."
  - cd src
  - dotnet restore
  only:
    - tags
  script:
    - dotnet build $PROJECT_NAME -c $CONFIG_TYPE -o npk -p:Version=$CI_BUILD_TAG

publishNuget:
  stage: publish
  only:
    - tags
  script:
    - echo 'Publishing NuGet package'
    - cd src/$PROJECT_NAME/npk/
    - dotnet nuget push *.$CI_BUILD_TAG.nupkg -k $NUGET_KEY -s https://www.nuget.org/api/v2/package